import { ImageProps } from "next/image";
import houses from "@/assets/landing.jpg";
type Contact = {
  user: string;
  email: string;
};

export type RentalType = {
  id: number;
  address: string;
  city: string;
  state: string;
  zipcode: string;
  name: string;
  about: string;
  amenities: string[];
  lifestyle: string[];
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  heating: string;
  cooling: string;
  buildingType: string;
  terms: string[];
  flooring: string[];
  contact: Contact;
  featuredImage: ImageProps["src"];
  images: ImageProps["src"][];
  available: boolean;
  availableAt?: Date;
  monthly: number;
};

export const properties: RentalType[] = [
  {
    id: 1,
    address: "123 Maple St",
    city: "Austin",
    state: "TX",
    zipcode: "78701",
    about:
      "Modern urban apartments in downtown Austin featuring spacious layouts, hardwood floors, and premium amenities like a pool and gym, perfect for pet-friendly city living.",
    name: "Maple Grove Apartments",
    amenities: ["Pool", "Gym", "WiFi"],
    lifestyle: ["Urban", "Pet Friendly"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 980,
    heating: "Central",
    cooling: "Central Air",
    buildingType: "Apartment",
    terms: ["12-month lease"],
    flooring: ["Hardwood"],
    contact: { user: "jdoe", email: "jdoe@maplegrove.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 2,
    address: "456 Oak Ave",
    city: "Denver",
    state: "CO",
    zipcode: "80203",
    about:
      "Comfortable suburban condo living with convenient parking and storage, offering a cozy one-bedroom layout ideal for professionals seeking flexibility and a quieter neighborhood.",
    name: "Oak Ridge Residences",
    amenities: ["Parking", "Storage"],
    lifestyle: ["Suburban"],
    bedrooms: 1,
    bathrooms: 1,
    sqft: 720,
    heating: "Gas",
    cooling: "Window Unit",
    buildingType: "Condo",
    terms: ["6-month lease", "12-month lease"],
    flooring: ["Carpet"],
    contact: { user: "asmith", email: "asmith@oakridge.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 3,
    address: "789 Pine Rd",
    city: "Seattle",
    state: "WA",
    zipcode: "98101",
    about:
      "Spacious townhomes designed for city living, featuring modern layouts, laminate flooring, and private balconies, ideal for families or roommates wanting room to breathe.",
    name: "Pine View Homes",
    amenities: ["Balcony"],
    lifestyle: ["City Living"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1350,
    heating: "Electric",
    cooling: "None",
    buildingType: "Townhome",
    terms: ["12-month lease"],
    flooring: ["Laminate"],
    contact: { user: "bwayne", email: "bwayne@pineview.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 4,
    address: "321 Cedar Ln",
    city: "Portland",
    state: "OR",
    zipcode: "97205",
    about:
      "Eco-conscious apartment living with concrete floors, bike storage, and laundry access, perfect for minimalists who value sustainability and flexible month-to-month leasing.",
    name: "Cedar Lane Flats",
    amenities: ["Laundry", "Bike Storage"],
    lifestyle: ["Eco Friendly"],
    bedrooms: 1,
    bathrooms: 1,
    sqft: 640,
    heating: "Electric",
    cooling: "Portable AC",
    buildingType: "Apartment",
    terms: ["Month-to-month"],
    flooring: ["Concrete"],
    contact: { user: "ckent", email: "ckent@cedarlane.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 5,
    address: "654 Birch Blvd",
    city: "Boise",
    state: "ID",
    zipcode: "83702",
    about:
      "Family-friendly single-family homes with generous space, modern comforts, and outdoor amenities, offering a welcoming environment for growing households in a peaceful neighborhood.",
    name: "Birchwood Living",
    amenities: ["WiFi", "Playground"],
    lifestyle: ["Family Friendly"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    heating: "Forced Air",
    cooling: "Central Air",
    buildingType: "Single Family",
    terms: ["12-month lease"],
    flooring: ["Tile", "Carpet"],
    contact: { user: "dprince", email: "dprince@birchwood.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 6,
    address: "98 Elm St",
    city: "Madison",
    state: "WI",
    zipcode: "53703",
    about:
      "Quiet and charming apartments with classic hardwood floors and radiator heating, ideal for residents seeking a calm, low-maintenance lifestyle in a serene setting.",
    name: "Elm Street Residences",
    amenities: ["Snow Removal"],
    lifestyle: ["Quiet"],
    bedrooms: 2,
    bathrooms: 1,
    sqft: 880,
    heating: "Radiator",
    cooling: "None",
    buildingType: "Apartment",
    terms: ["12-month lease"],
    flooring: ["Hardwood"],
    contact: { user: "mmiller", email: "mmiller@elmstreet.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 7,
    address: "777 Sunset Blvd",
    city: "Los Angeles",
    state: "CA",
    zipcode: "90028",
    about:
      "Luxury high-rise living featuring rooftop views, concierge services, and premium amenities, perfectly located for residents who enjoy nightlife, entertainment, and modern city living.",
    name: "Sunset Towers",
    amenities: ["Rooftop", "Concierge", "Gym"],
    lifestyle: ["Luxury", "Nightlife"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    heating: "Central",
    cooling: "Central Air",
    buildingType: "High-Rise",
    terms: ["12-month lease"],
    flooring: ["Hardwood"],
    contact: { user: "rjohnson", email: "rjohnson@sunsettowers.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 8,
    address: "222 Lakeview Dr",
    city: "Chicago",
    state: "IL",
    zipcode: "60601",
    about:
      "Stylish waterfront lofts with concrete floors and lake access, offering modern comfort and scenic surroundings for residents who value design and location.",
    name: "Lakeview Lofts",
    amenities: ["Lake Access"],
    lifestyle: ["Waterfront"],
    bedrooms: 1,
    bathrooms: 1,
    sqft: 760,
    heating: "Central",
    cooling: "Central Air",
    buildingType: "Loft",
    terms: ["12-month lease"],
    flooring: ["Concrete"],
    contact: { user: "tlee", email: "tlee@lakeviewlofts.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 9,
    address: "19 Hillcrest Rd",
    city: "San Jose",
    state: "CA",
    zipcode: "95112",
    about:
      "Spacious suburban homes with modern finishes, private gardens, and ample living space, ideal for large families seeking comfort, privacy, and convenience.",
    name: "Hillcrest Homes",
    amenities: ["Garden"],
    lifestyle: ["Suburban"],
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    heating: "Forced Air",
    cooling: "Central Air",
    buildingType: "Single Family",
    terms: ["12-month lease"],
    flooring: ["Tile", "Hardwood"],
    contact: { user: "knguyen", email: "knguyen@hillcrest.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 10,
    address: "808 River St",
    city: "Savannah",
    state: "GA",
    zipcode: "31401",
    about:
      "Elegant riverfront apartments blending historic charm with modern comforts, featuring hardwood floors and scenic views in one of Savannah’s most desirable locations.",
    name: "Riverwalk Residences",
    amenities: ["River View"],
    lifestyle: ["Historic"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    heating: "Heat Pump",
    cooling: "Central Air",
    buildingType: "Apartment",
    terms: ["12-month lease"],
    flooring: ["Hardwood"],
    contact: { user: "hjackson", email: "hjackson@riverwalk.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 11,
    address: "41 Aspen Way",
    city: "Boulder",
    state: "CO",
    zipcode: "80302",
    about:
      "Cozy mountain-inspired apartments with fireplaces and peaceful surroundings, perfect for residents who enjoy a relaxed lifestyle close to nature and outdoor recreation.",
    name: "Aspen Way Apartments",
    amenities: ["Fireplace"],
    lifestyle: ["Mountain"],
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    heating: "Gas",
    cooling: "None",
    buildingType: "Apartment",
    terms: ["9-month lease", "12-month lease"],
    flooring: ["Carpet"],
    contact: { user: "lmartin", email: "lmartin@aspenway.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 12,
    address: "500 Harbor Dr",
    city: "San Diego",
    state: "CA",
    zipcode: "92101",
    about:
      "Coastal condo living with marina access and resort-style amenities, offering a relaxed seaside lifestyle just steps away from downtown San Diego attractions.",
    name: "Harbor Point Living",
    amenities: ["Marina Access", "Pool"],
    lifestyle: ["Coastal"],
    bedrooms: 1,
    bathrooms: 1,
    sqft: 820,
    heating: "Electric",
    cooling: "Central Air",
    buildingType: "Condo",
    terms: ["12-month lease"],
    flooring: ["Tile"],
    contact: { user: "srodriguez", email: "srodriguez@harborpoint.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 13,
    address: "73 Highland Ave",
    city: "Cambridge",
    state: "MA",
    zipcode: "02139",
    about:
      "Student-friendly apartments near campus with spacious layouts, hardwood floors, and dedicated study areas, ideal for shared living and academic-focused lifestyles.",
    name: "Highland Court",
    amenities: ["Study Room"],
    lifestyle: ["Student Friendly"],
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1150,
    heating: "Radiator",
    cooling: "Window Unit",
    buildingType: "Apartment",
    terms: ["12-month lease"],
    flooring: ["Hardwood"],
    contact: { user: "aparker", email: "aparker@highlandcourt.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 14,
    address: "600 Desert Rd",
    city: "Phoenix",
    state: "AZ",
    zipcode: "85004",
    about:
      "Resort-style apartments featuring pools and central air, designed to provide a refreshing, modern retreat while staying comfortable in Phoenix’s warm desert climate.",
    name: "Desert Bloom Apartments",
    amenities: ["AC", "Pool"],
    lifestyle: ["Resort Style"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    heating: "Electric",
    cooling: "Central Air",
    buildingType: "Apartment",
    terms: ["12-month lease"],
    flooring: ["Tile"],
    contact: { user: "wgreen", email: "wgreen@desertbloom.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
  {
    id: 15,
    address: "9 Forest Path",
    city: "Burlington",
    state: "VT",
    zipcode: "05401",
    about:
      "Charming cottages surrounded by nature, offering wood floors, trail access, and fire pits for residents seeking tranquility and an outdoor-focused lifestyle.",
    name: "Forest Path Cottages",
    amenities: ["Trail Access", "Fire Pit"],
    lifestyle: ["Nature"],
    bedrooms: 2,
    bathrooms: 1,
    sqft: 860,
    heating: "Wood Stove",
    cooling: "None",
    buildingType: "Cottage",
    terms: ["12-month lease"],
    flooring: ["Wood"],
    contact: { user: "ebrown", email: "ebrown@forestpath.com" },
    featuredImage: houses,
    images: [houses, houses, houses, houses, houses, houses],
    monthly: 1500.0,
    available: true,
  },
];
